# Generated by Django 3.0.5 on 2020-05-01 07:11

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('todoapp', '0006_auto_20200422_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
