# Generated by Django 3.0.5 on 2020-05-04 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0008_auto_20200502_0635'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='shared_users_str',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
