# Generated by Django 3.0.5 on 2020-05-05 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('todoapp', '0011_auto_20200504_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todo', to='authapp.User'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
